# New Section

## **Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# **Importing dataset**

In [ ]:
#@title Default title text
dataset=pd.read_csv("Data.csv")
indep=dataset.iloc[:,:-1].values
dep=dataset.iloc[:,-1].values
print(dep)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## **Taking care of missing data**

In [ ]:
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(indep[:,1:3])
indep[:,1:3]=imputer.transform(indep[:,1:3])
print(indep)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encode Categorical data

In [ ]:
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
indep=np.array(ct.fit_transform(indep))
print(indep)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
le=LabelEncoder()
dep=le.fit_transform(dep)
print(dep)

[0 1 0 0 1 1 0 1 0 1]


## **Splitting data into trainning and testing set**

In [ ]:
indep_train,indep_test,dep_train,dep_test=train_test_split(indep,dep,test_size=0.2,random_state=1)

# **Feature Scaling**

In [ ]:
sc=StandardScaler()
indep_train[:,3:]=sc.fit_transform(indep_train[:,3:])
indep_test[:,3:]=sc.transform(indep_test[:,3:])
print(indep_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
